### PR TITLE
Allysonc add atlanta

### PR DESCRIPTION
**Pull request by allysonc**
add items under headers
@stevencericson what would you like to do if you ever visit Atlanta?
:bear:

### CODE REVIEW

**Comment by yvsatyaprasad** [comment]
# Hello Atlanta!!!

**Comment by yvsatyaprasad** [comment]
- [ ] Braves

- [ ] Hawks!!

**Comment by mixolidia** [comment]
Hey @yvsatyaprasad I like the outdoors, vegetarian restaurants and baked goods. Where can I do that in Atlanta? :)

**Comment by allysonc** [comment]
Thanks! Piedmont Park is a great place to go in Atlanta. There's a lot of great restaurants nearby.

**Pull request merged**
