### PR TITLE
Digitalemcee add hometown

### PR DESCRIPTION
**Pull request by digitalemcee**
Any other things you like to do in Los Angeles, @mendyslaton?

Outside of places and eats? 🍴 🚲 ☀️

### CODE REVIEW

**Comment by RustyBee2016** [comment]
Where are the best beaches near LA?

**Comment by RustyBee2016** [comment]
@digitalemcee How long have you lived there?

**Comment by digitalemcee** [comment]
@RustyBee2016 Born and raised in LA, lived there 33 years before moving to South Korea! ✈️

**Comment by digitalemcee** [comment]
I love Redondo Beach and Manhattan Beach. Small beaches and not too crowded like Venice Beach. ☀️

**Pull request merged**
