### PR TITLE
Githubteacher local

### PR DESCRIPTION
**Pull request by githubteacher**
What kind of food do people expect when they visit Orlando?

### CODE REVIEW

**Comment by brianamarie** [comment]
I expect tacos but I have no idea why...

**Comment by deepamathur** [comment]
Asian cuisines :)

**Comment by krgroseclose** [comment]
Asian tacos for everyone!

**Comment by kgodoy** [comment]
I would to visit Miami!

**Comment by jcon5** [comment]
Mickey Bars and Dole whips!

**Comment by mixolidia** [comment]
I like vegetarian Caribbean food. Any good places in Orlando?

**Comment by kgodoy** [comment]
*I would :heart:  to visit Miami!

**Comment by markwittman** [comment]
Pizza and Fish, but not combined.

**Pull request merged**
